### ISSUE TITLE
Evaluate Dagger instead of Make/GH Action

### ISSUE THREAD

**Issue by Vad1mo** [goharbor/harbor-cli#22]
This is not one of the top priorities, but in my opinion it would make sense to replace the Makefile and large part of the workflows with https://dagger.io/ 

Some benefits I see
- Easy way to spin up a local env from scratch, 
- better end-to-end testing

**Comment by bishal7679** [comment]
Nice One! 
tried once but not implemented. Let's write a script with it

**Comment by amands98** [comment]
My take ->
Considering infrequent CI system changes, introducing Dagger as an intermediary layer may not be necessary if you switch systems rarely. 

I see fewer projects adopting Dagger.

https://medium.com/devstream/an-honest-look-at-dagger-fae07986bfc1

**Comment by JaeAeich** [comment]
The main issue I see is the logs, with GH actions it is easier for the team to figure out the problem from the logs on github itself, rather than going and running locally. Plus there won't be enough granularity in "task"/"actions" anymore, yeah we can run them individually if we want to do it on gh actions but that means for us to again write workflows which brings us back to square 1. The biggest advantage of dagger I see is being able to run pipelines locally but if someone cared that much they can do so with [ACT](https://github.com/nektos/act). And the other cool feature it CUE and being able to generate containers without a set Dockerfile but with code, which might be useful but the tradeoff imo outweighs the other challenges.

**Comment by tylerauerbeck** [comment]
@Vad1mo Looks like the cutover to dagger has happened, so I think this one can probably be closed?
